export const imagens = {
    Logo: '/imagens/Logo.svg',
    Logo_2: '/imagens/Logo_2.svg',
    Logo_3: '/imagens/Logo_3.svg',
    Hero: '/imagens/hero.png',
    Arrow: '/imagens/right-arrow.png',
    Hero_470: '/imagens/hero_470.png',
    Gray_Circle:'/imagens/gray_circle.png',
    Blue_Circle:'/imagens/blue_circle.png',
    Warning: '/imagens/warning.png',
    Bipolar: '/imagens/bipolar.png',
    Goal: '/imagens/goal.png',
    Growing: '/imagens/growing.png',
    Therapy: '/imagens/therapy.png',
    Hand_Phone: '/imagens/hand_phone.png',
    Feature: '/imagens/cta.png',
    Talk_1: '/imagens/talk_1.png',
    Talk_2: '/imagens/talk_2.png',
    Star_1: '/imagens/star_1.png',
    Star_2: '/imagens/star_2.png',
    Arrow_Up: '/imagens/arrow_up.png',
    Face_1: '/imagens/face1.png',
    Therapy_1: '/imagens/therapy_1.png',
    Ellipse: '/imagens/ellipse.png',
    Check: '/imagens/check.png',
    Arrow_Blue: '/imagens/arrow_blue.png',
    Profession1: '/imagens/profession1.png',
    Profession2: '/imagens/profession2.png',
    Profession3: '/imagens/profession3.png',
    Circle_Gradient: '/imagens/gradient.png',
    Google_Play: '/imagens/google_play.png',
    App_Store: '/imagens/app_store.png',
    News_1: '/imagens/news_1.png',
    News_2: '/imagens/news_2.png',
    News_3: '/imagens/news_3.png',
    Button_Plus: '/imagens/button_plus.png'
}